$(".ul-yi").click(function () {
  $(".ul-yi i").show();
  $(".ul-yi b").show();
  $(".youbian").show();
  $(".san-san").show();
  $(".banman").show();
  $(".san-si").show();

  $(".qh-er").hide();
  $(".qh-yi").hide();
  $(".ul-er i").hide();
  $(".ul-er b").hide();
  $(".ul-san i").hide();
  $(".ul-san b").hide();
  $(".san-wu").hide();
  $(".san-liu").hide();
  $(".youbiant").hide();
  $(".youbiant img").hide();
  $(".youbiantyi").hide();
  $(".youbiantyi img").hide();
  $(".qh-san").hide();
  $(".ul-wu i").hide();
  $(".ul-wu b").hide();
  $(".san-qi").hide();
  $(".youbianter").hide();
  $(".youbianter img").hide();
  $(".qh-si").hide();
  $(".ul-liu i").hide();
  $(".ul-liu b").hide();
  $(".san-ba").hide();
  $(".youbiantsan").hide();
  $(".youbiantsan img").hide();
});

$(".ul-er").click(function () {
  $(".ul-yi i").hide();
  $(".ul-yi b").hide();
  $(".ul-san i").hide();
  $(".ul-san b").hide();
  $(".youbian").hide();
  $(".san-san").hide();
  $(".san-liu").hide();
  $(".banman").hide();
  $(".youbiantyi").hide();
  $(".youbiantyi img").hide();
  $(".qh-er").hide();
  $(".qh-san").hide();
  $(".ul-wu i").hide();
  $(".ul-wu b").hide();
  $(".san-qi").hide();
  $(".youbianter").hide();
  $(".youbianter img").hide();
  $(".qh-si").hide();
  $(".ul-liu i").hide();
  $(".ul-liu b").hide();
  $(".san-ba").hide();
  $(".youbiantsan").hide();
  $(".youbiantsan img").hide();

  $(".san-si").show();
  $(".qh-yi").show();
  $(".ul-er i").show();
  $(".ul-er b").show();
  $(".san-wu").show();
  $(".youbiant").show();
  $(".youbiant img").show();
});

$(".ul-san").click(function () {
  $(".ul-yi i").hide();
  $(".ul-yi b").hide();
  $(".ul-er i").hide();
  $(".ul-er b").hide();
  $(".youbian").hide();
  $(".san-san").hide();
  $(".san-wu").hide();
  $(".banman").hide();
  $(".youbiant").hide();
  $(".youbiant img").hide();
  $(".qh-yi").hide();
  $(".qh-san").hide();
  $(".ul-wu i").hide();
  $(".ul-wu b").hide();
  $(".san-qi").hide();
  $(".youbianter").hide();
  $(".youbianter img").hide();
  $(".qh-si").hide();
  $(".ul-liu i").hide();
  $(".ul-liu b").hide();
  $(".san-ba").hide();
  $(".youbiantsan").hide();
  $(".youbiantsan img").hide();

  $(".san-si").show();
  $(".qh-er").show();
  $(".ul-san i").show();
  $(".ul-san b").show();
  $(".san-liu").show();
  $(".youbiantyi").show();
  $(".youbiantyi img").show();
});

$(".ul-wu").click(function () {
  $(".ul-yi i").hide();
  $(".ul-yi b").hide();
  $(".ul-er i").hide();
  $(".ul-er b").hide();
  $(".ul-san i").hide();
  $(".ul-san b").hide();
  $(".youbian").hide();
  $(".san-san").hide();
  $(".san-wu").hide();
  $(".banman").hide();
  $(".youbiant").hide();
  $(".youbiant img").hide();
  $(".youbiantyi").hide();
  $(".youbiantyi img").hide();
  $(".qh-yi").hide();
  $(".qh-er").hide();
  $(".san-liu").hide();
  $(".qh-si").hide();
  $(".ul-liu i").hide();
  $(".ul-liu b").hide();
  $(".san-ba").hide();
  $(".youbiantsan").hide();
  $(".youbiantsan img").hide();

  $(".san-si").show();
  $(".qh-san").show();
  $(".ul-wu i").show();
  $(".ul-wu b").show();
  $(".san-qi").show();
  $(".youbianter").show();
  $(".youbianter img").show();
});

$(".ul-liu").click(function () {
  $(".ul-yi i").hide();
  $(".ul-yi b").hide();
  $(".ul-er i").hide();
  $(".ul-er b").hide();
  $(".ul-san i").hide();
  $(".ul-san b").hide();
  $(".youbian").hide();
  $(".san-san").hide();
  $(".san-wu").hide();
  $(".banman").hide();
  $(".youbiant").hide();
  $(".youbiant img").hide();
  $(".youbiantyi").hide();
  $(".youbiantyi img").hide();
  $(".qh-yi").hide();
  $(".qh-er").hide();
  $(".san-liu").hide();
  $(".qh-san").hide();
  $(".ul-wu i").hide();
  $(".ul-wu b").hide();
  $(".san-qi").hide();
  $(".youbianter").hide();
  $(".youbianter img").hide();

  $(".san-si").show();
  $(".qh-si").show();
  $(".ul-liu i").show();
  $(".ul-liu b").show();
  $(".san-ba").show();
  $(".youbiantsan").show();
  $(".youbiantsan img").show();
});
